apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-node-watchdog
  labels:
    app: aws-node-watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-node-watchdog
  template:
    metadata:
      labels:
        app: aws-node-watchdog
    spec:
      containers:
      - name: aws-node-watchdog
        image: 6fusion/aws-k8s-node-watchdog:alpha
        resources:
          requests:
            memory: "10Mi"
