apiVersion: v1
kind: ServiceAccount
metadata:
  name: watchdog
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchdog-node-admin
subjects:
- kind: ServiceAccount
  name: watchdog
  apiGroup: ""
  namespace: default
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aws-node-watchdog
  namespace: default
  labels:
    app: aws-node-watchdog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-node-watchdog
  template:
    metadata:
      labels:
        app: aws-node-watchdog
    spec:
      serviceAccountName: watchdog
      containers:
      - name: aws-node-watchdog
        image: 6fusion/aws-k8s-node-watchdog:0.2
        resources:
          requests:
            memory: "10Mi"
